### ISSUE TITLE
工信部备案，无法访问

### ISSUE THREAD

**Issue by zsj1029** [jinxin1517/vite-react-ts-admin#10]
工信部备案，无法访问

**Comment by jinxin1517** [comment]
最近服务器换腾讯云了，在备案。可以先拉项目，本地跑看看。接口项目对应https://github.com/jinxin1517/nest-admin，都选对应分支跑起来就行了

**Comment by jinxin1517** [comment]
链接已经修改，现在应该可以了

**Comment by zsj1029** [comment]
http://110.40.192.199:3004/#/Problem/Personal/vite-react-admin
不行哦，打开白屏
console
···
110.40.192.199/:10 
        
       GET http://pv.sohu.com/cityjson?ie=utf-8 net::ERR_ABORTED 403 (Forbidden)
umi.js:1 
        
       TypeError: Cannot read properties of undefined (reading 'cip')
    at L (umi.js:1)
    at mi (umi.js:1)
    at Fl (umi.js:1)
    at Qc (umi.js:1)
    at Fc (umi.js:1)
    at Oc (umi.js:1)
    at Sc (umi.js:1)
    at hs (umi.js:1)
    at umi.js:1
    at Lc (umi.js:1)
       Uncaught TypeError: Cannot read properties of undefined (reading 'cip')
    at L (umi.js:1)
    at mi (umi.js:1)
    at Fl (umi.js:1)
    at Qc (umi.js:1)
    at Fc (umi.js:1)
    at Oc (umi.js:1)
    at Sc (umi.js:1)
    at hs (umi.js:1)
    at umi.js:1
    at Lc (umi.js:1)

跨源读取阻止(CORB)功能阻止了 MIME 类型为 text/html 的跨源响应https://dnspod.qcloud.com/static/webblock.html?d=assets.jinxinapp.cn。有关详细信息，请参阅 https://www.chromestatus.com/feature/5629709824032768。
···

**Comment by jinxin1517** [comment]
http://110.40.192.199:3004/#/Problem/Personal/vite-react-admin    这个链接我找人试了，自己手机打开试了，是可以的呀

**Comment by zsj1029** [comment]
手机确实可以
pc浏览器不行
http://pv.sohu.com/cityjson?ie=utf-8 
Status Code: 403 Forbidden
chrome96
edge chrome都试了不行

**Comment by zsj1029** [comment]
关闭翻墙就好了，很奇怪

**Comment by jinxin1517** [comment]
是不是pc有缓存或者电脑上开了代理之类的

**Comment by jinxin1517** [comment]
因为我国内ip吧，可能

**Comment by zsj1029** [comment]
缓存都禁用了，只要开了代理就不行
看了下，代理打开http://pv.sohu.com/cityjson?ie=utf-8 403请求不到
关了后，这个数据能拿到就正常了
搜狐pv那边估计禁止国外访问，后续js报错就走不下去页面打不开了

**Comment by jinxin1517** [comment]
那就好👌

**Comment by zsj1029** [comment]
thx
